### ISSUE TITLE
Some work as contribution, some not

### ISSUE THREAD

**Issue by fosterlynn** [valnet/valuenetwork#448] opened 2015-10-20 00:44 UTC
From Fabio on loomio:

Some contributors such as researchers will contribute to the project while doing it as part of a paid job.

Should this kind of contributions be registered in the VAS ? How should this be taken into account for our value equation (financial acknowledgment of former contributions) ?

from Lynn

Just FYI: One way to differentiate in the VAS is to create a different type of work for work that won’t be part of a value equation, or will need a different formula in a value equation - such as work paid from another source. Then you can filter by type of work and apply different formulas in a value equation.

Another thought: We have a flag on the economic events (so this includes work, financial contributions, etc.) saying whether the event is a contribution or not. We mostly haven’t exposed this flag, we just make assumptions. We could expose the flag (which we need to do for payments anyhow now) and then people could select if it should be a contribution for payback or not.

There might be other ways we could deal with it in the software, could think about it more.

This is if people would like to record all the work done, whether it will be paid or not, which there are reasons to do. Like to be able to accurately understand what it took to do a project, for future estimates, looking for where process improvements can be made, etc.

from Fabio:

That seems a very good solution, so that we both try to capture all work done and have differentiated acknowledgments. Thanks !

**Comment by ahdinosaur** [comment] 2015-10-20 03:33
VAS = value accounting system?

**Comment by gcassel** [comment] 2015-10-20 06:12
"This is if people would like to record all the work done, whether it will be paid or not, which there are reasons to do. Like to be able to accurately understand what it took to do a project, for future estimates, looking for where process improvements can be made, etc."

^   Sounds great @fosterlynn .  I still need to get much better oriented here, but I don't currently think that financial compensation should be a focus of value accounting formulae.  Information and documentation of processes and transfers are valuable, regardless of big financial variables such as:

1. a specific OVN may assign financial compensation to certain predefined types of tasks
2.   an OVN may compensate agents (financially or otherwise) for adding preexisting media from external sources-- and, it may compensate them differently depending on whether they are or aren't the author(s) of said media.
3. agents within an OVN may engage in a variety of exchanges, potentially including financial compensation

Financial compensation is a complex and often IMO thorny issue, especially in projects and businesses.  (Am I correct in thinking that VAS is supposed to be useful for projects and businesses as well as peer production networks?)   This is partly because many roles hold direct or indirect positional coercive authority.  That coercive authority can be viewed as a form of compensation in itself, especially when it's maximally associated with creativity and minimally associated with personal accountability.   This is why some volunteer positions are highly desirable, and the supply of volunteers may far outstrip the demand.   Conversely, many non-creative and boring tasks may be undervalued and unassigned.  They may be undone, or get done by chronically responsible people (who may or may not derive great value from the network), **or**  by 'low-ranking' people who think they 'need' to build social capital.   (Which they may or may not *get*, without a value accounting system.)

**Comment by bhaugen** [comment] 2015-10-20 10:25
@gcassel 
> Am I correct in thinking that VAS is supposed to be useful for projects and businesses as well as peer production networks?

As presently configured, traditional businesses would have some problems. We had a recent conversation with somebody who wanted to use the system for a regional business ecosystem, which we think is an interesting idea, and we discussed some of the things they would probably want to change. We also made it clear that we did not personally intend to change them, but it was open source software and if they followed the license, they could fork it and make the changes themselves.

I don't know if they will do so. A lot of people talk, fewer do.

I would say the software would be potentially useful for joint ventures, too.

**Comment by fosterlynn** [comment] 2015-10-20 13:01
@ahdinosaur yes VAS = Value Accounting System.  This software has had a lot of names, we're hoping to get a new "permanent" one soon.  Now it is mostly NRP for Network Resource Planning, but some people still call it VAS and some call it NRP/VAS, seeing the resource planning and the accounting as possibly distinct.  Nobody calls it valnet any more.  :)

@gcassel yes many complex issues.  We're basically supporting peer production groups as they make these decisions for themselves.  In terms of getting oriented, there's a lot of info on the wiki here, maybe way more than you want. :)

**Comment by gcassel** [comment] 2015-10-20 17:40
@bhaugen thanks much for the info.  Not that you need my blessing, but FYI I fully support a strong focus on peer production networks.   They desperately need viable and sustainable economic models.  (Hey no pressure!)

People can fork your software to suit businesses and business ecosystems, if enough people are interested.   Also, all projects and businesses have communities, and IMO healthy public projects should have intentional community commons, which could operate by NRP/VAS models and software.   So, I guess that new styles of team-based project management/ social enterprise can develop a symbiotic relationship with NRP/VAS approaches to public media commons.

In the long term, as value accounting improves for autonomous peers, *and* as projects develop much more inclusive, distributed investment, management and administration practices, perhaps the distinction between 'network' and 'project' seems to mostly dissolve?

**Comment by fosterlynn** [comment] 2015-10-20 18:51
@gcassel hey thanks for popping in and for the support!  :)

**Comment by fosterlynn** [comment] 2015-11-05 00:54
@bhaugen I think the best solution for this is to expose the is_contribution checkbox for work events on the process logging page.  Then instead of assuming all work is_contribution when we save, use the checkbox.  Default to is_contribution = True on the forms.

Note, we need to do this for Payment events on purchase contributions too, see issue #366 .

**Comment by bhaugen** [comment] 2015-11-05 16:08
@fosterlynn - we will need to filter for is_contribution=True in value equations, too.

And another question: do you think "is contribution" will communicate to normal people? It comes from Sensorica, where @TiberiusB differentiated contributions and gifts. Contributions were potentially eligible for value equation distributions, gifts were not. We could explain all that, but is there a better word?

**Comment by fosterlynn** [comment] 2015-11-05 16:33
@bhaugen "Participates in value equations" ??

I agree "contribution" is pretty much Sensorica terminology.

**Comment by bhaugen** [comment] 2015-11-05 16:44
It's broader than Sensorica. There's a whole set of literature about "contribution economy". But as a word, it is so suggestive of gift, like, I am contributing this to the cause, and I expect confusion.

**Comment by fosterlynn** [comment] 2015-11-05 16:54
Yes agree - we need something different.... and need to make it clear it refers to this event only.

**Comment by bhaugen** [comment] 2015-12-15 13:24
Done for work logging forms on the process logging page.

**Comment by bhaugen** [comment] 2015-12-17 18:58
Done for nonproduction work logging, too.

**Comment by bhaugen** [comment] 2015-12-17 18:59
I'm closing this issue about work logging. The only other kind of work logging I am aware of is connected purchase contributions, where I assume the only reason someone would even log their work in that situation is to get credit for value equations.

**Closed by bhaugen** 2015-12-17 18:59 UTC
